# Generated by Django 3.1.3 on 2021-01-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210103_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payee',
            field=models.CharField(max_length=30, verbose_name='payee'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer',
            field=models.CharField(max_length=30, verbose_name='payer'),
        ),
    ]
