# Generated by Django 3.1.3 on 2021-01-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete tag')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('real_name', models.CharField(max_length=50, verbose_name='real_name')),
                ('idcard', models.CharField(default='', max_length=50, verbose_name='idcard')),
                ('account_balance', models.IntegerField(default=0, verbose_name='account_balance')),
                ('user_publickey', models.TextField(verbose_name='user_publickey')),
            ],
            options={
                'db_table': 's_user_passport',
            },
        ),
    ]
