# Generated by Django 3.1.3 on 2021-01-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210103_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='account_balance',
            field=models.FloatField(default=0.0, verbose_name='account_balance'),
        ),
    ]
